## Data cleaning and initial EDA
1. What columns do we keep?
2. What is an acceptable null count to get away with? Should we fill in with mean of other columns, or some ridiculous value?
3. Missing demographic data from 3 counties, which should be ok to omit. Can still include in initial chloropleth plots, but not in predictions. 
4. Classes needed? Probably not for cleaning. Functions? Also unlikely for cleaning since this set is already pretty clean. One hot encoder for categorical variables like rural/urban (metro, adjacent to metro, rural)

In [63]:
%load_ext autoreload
%autoreload 2

# Code for cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [64]:
data = pd.read_csv('data/election-context-2018.csv')

In [65]:
# Show all columns
pd.set_option("display.max_columns", 40)
data.head()

,state,county,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,demsen16,repsen16,othersen16,demhouse16,rephouse16,otherhouse16,demgov16,repgov16,othergov16,repgov14,demgov14,othergov14,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,age65andolder_pct,median_hh_inc,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,ruralurban_cc
0,Alabama,Autauga,1001,18172,5936,865,17379,6363,190,6331.0,18220.0,62.0,7544.0,14315.0,2258.0,NaN,NaN,NaN,9427.0,3638.0,0.0,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,13.978456,53099.0,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,2.0
1,Alabama,Baldwin,1003,72883,18458,3874,66016,18424,898,19145.0,74021.0,248.0,0.0,76995.0,1991.0,NaN,NaN,NaN,37650.0,8416.0,0.0,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,18.714851,51365.0,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,3.0
2,Alabama,Barbour,1005,5454,4871,144,5550,5912,47,4777.0,5436.0,16.0,5297.0,4286.0,463.0,NaN,NaN,NaN,3111.0,3651.0,0.0,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,16.528895,33956.0,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,6.0
3,Alabama,Bibb,1007,6738,1874,207,6132,2202,86,2082.0,6612.0,17.0,1971.0,6670.0,15.0,NaN,NaN,NaN,3525.0,1368.0,0.0,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,14.885699,39776.0,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,1.0
4,Alabama,Blount,1009,22859,2156,573,20757,2970,279,2980.0,22169.0,48.0,2390.0,22367.0,47.0,NaN,NaN,NaN,12074.0,2178.0,0.0,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,17.192916,46212.0,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,1.0

In [66]:
data.columns

Index(['state', 'county', 'fips', 'trump16', 'clinton16', 'otherpres16',
       'romney12', 'obama12', 'otherpres12', 'demsen16', 'repsen16',
       'othersen16', 'demhouse16', 'rephouse16', 'otherhouse16', 'demgov16',
       'repgov16', 'othergov16', 'repgov14', 'demgov14', 'othergov14',
       'total_population', 'cvap', 'white_pct', 'black_pct', 'hispanic_pct',
       'nonwhite_pct', 'foreignborn_pct', 'female_pct', 'age29andunder_pct',
       'age65andolder_pct', 'median_hh_inc', 'clf_unemploy_pct', 'lesshs_pct',
       'lesscollege_pct', 'lesshs_whites_pct', 'lesscollege_whites_pct',
       'rural_pct', 'ruralurban_cc'],
      dtype='object')

In [67]:
import pandas as pd
import io
import requests
url="https://github.com/mkpetterson/data/blob/master/hate-crimes/hate_crimes.csv"
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))

ParserError: Error tokenizing data. C error: Expected 1 fields in line 49, saw 2

In [ ]:
data.info()

In [68]:
data.columns[9:21]

Index(['demsen16', 'repsen16', 'othersen16', 'demhouse16', 'rephouse16',
       'otherhouse16', 'demgov16', 'repgov16', 'othergov16', 'repgov14',
       'demgov14', 'othergov14'],
      dtype='object')

In [69]:
# Drop columns and rows with na
data = data.drop(columns = data.columns[9:21])
data = data.dropna()

In [70]:
data.head()

,state,county,fips,trump16,clinton16,otherpres16,romney12,obama12,otherpres12,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,age65andolder_pct,median_hh_inc,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,ruralurban_cc
0,Alabama,Autauga,1001,18172,5936,865,17379,6363,190,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,13.978456,53099.0,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,2.0
1,Alabama,Baldwin,1003,72883,18458,3874,66016,18424,898,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,18.714851,51365.0,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,3.0
2,Alabama,Barbour,1005,5454,4871,144,5550,5912,47,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,16.528895,33956.0,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,6.0
3,Alabama,Bibb,1007,6738,1874,207,6132,2202,86,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,14.885699,39776.0,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,1.0
4,Alabama,Blount,1009,22859,2156,573,20757,2970,279,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,17.192916,46212.0,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,1.0

## Let's create new features
1. Get percentage of votes for trump, clinton, other instead of raw numbers
2. Same for romney, obama, other in 2012?
3. Column for percentage of voting age population who voted

In [71]:
def get_percentage(df):
    """ Creates new column of percentage of votes"""
    
    total_votes16 = data['trump16'] + data['clinton16'] + data['otherpres16']
    total_votes12 = data['romney12'] + data['obama12'] + data['otherpres12']
    
    cols16 = ['trump16', 'clinton16', 'otherpres16']
    cols12 = ['romney12', 'obama12', 'otherpres12']
    
    for colname in cols16:
        new_name = colname + '_pct'    
        df[new_name] = 100*df[colname]/total_votes16
    
    for colname in cols12:
        new_name = colname + '_pct'
        df[new_name] = 100*df[colname]/total_votes12
        
    data['cvap_pct'] = 100*total_votes16/data['cvap']
    
    return None

In [72]:
get_percentage(data)

In [73]:
# Let's store population data separately. 
population_data = data[['state', 'county', 'total_population']]
population_data.head()

     state   county  total_population
0  Alabama  Autauga           55049.0
1  Alabama  Baldwin          199510.0
2  Alabama  Barbour           26614.0
3  Alabama     Bibb           22572.0
4  Alabama   Blount           57704.0

In [74]:
# Now drop other columns
columns_to_drop = ['trump16', 'clinton16', 'otherpres16', 'romney12', 'obama12', 'otherpres12',
                  'cvap', 'total_population']

In [75]:
data = data.drop(columns = columns_to_drop)

In [76]:
data.head()

,state,county,fips,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,age65andolder_pct,median_hh_inc,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,ruralurban_cc,trump16_pct,clinton16_pct,otherpres16_pct,romney12_pct,obama12_pct,otherpres12_pct,cvap_pct
0,Alabama,Autauga,1001,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,13.978456,53099.0,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,2.0,72.766588,23.769671,3.463741,72.618252,26.587832,0.793916,61.373802
1,Alabama,Baldwin,1003,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,18.714851,51365.0,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,3.0,76.545712,19.385601,4.068687,77.358269,21.589444,1.052286,62.736377
2,Alabama,Barbour,1005,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,16.528895,33956.0,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,6.0,52.096666,46.527844,1.375490,48.223130,51.368494,0.408376,51.381595
3,Alabama,Bibb,1007,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,14.885699,39776.0,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,1.0,76.403220,21.249575,2.347205,72.826603,26.152019,1.021378,50.136441
4,Alabama,Blount,1009,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,17.192916,46212.0,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,1.0,89.334844,8.425825,2.239331,86.465884,12.371907,1.162209,60.306387

## Now do OHE on rural columns
But first, figure out which values to keep
### ruralurban\_cc
- **Description**: rural-urban continuum codes
- **Year/s**: 2013
- **Source**: [USDA Economic Research Service](https://www.ers.usda.gov/data-products/rural-urban-continuum-codes/)
- **Coding**:

| Code | Description |
| --- | --- |
| 1 | Counties in metro areas of 1 million population or more |
| 2 | Counties in metro areas of 250,000 to 1 million population |
| 3 | Counties in metro areas of fewer than 250,000 population |
| 4 | Urban population of 20,000 or more, adjacent to a metro area |
| 5 | Urban population of 20,000 or more, not adjacent to a metro area |
| 6 | Urban population of 2,500 to 19,999, adjacent to a metro area |
| 7 | Urban population of 2,500 to 19,999, not adjacent to a metro area |
| 8 | Completely rural or less than 2,500 urban population, adjacent to a metro area |
| 9 | Completely rural or less than 2,500 urban population, adjacent to a metro area |


1. Group all metro areas together

In [79]:
def ohe_rural(data):
    data['metro'] = data['ruralurban_cc'].apply(lambda x: 1 if x <= 3.0 else 0)
    data['rural'] = data['ruralurban_cc'].apply(lambda x: 1 if x >= 8.0 else 0)
    data['urban_metroadj'] = data['ruralurban_cc'].apply(lambda x: 1 if (x==4) or (x==6) else 0)
    data['urban_not_metroadj'] = data['ruralurban_cc'].apply(lambda x: 1 if (x==5) or (x==7) else 0)
    
    return None

In [80]:
ohe_rural(data)

In [83]:
# Save cleaned data and population data
data.to_csv('data/cleaned_data.csv')
population_data.to_csv('data/population.csv')

In [82]:
data.index.values

array([   0,    1,    2, ..., 3111, 3112, 3113])

In [84]:
data.head()

,state,county,fips,white_pct,black_pct,hispanic_pct,nonwhite_pct,foreignborn_pct,female_pct,age29andunder_pct,age65andolder_pct,median_hh_inc,clf_unemploy_pct,lesshs_pct,lesscollege_pct,lesshs_whites_pct,lesscollege_whites_pct,rural_pct,ruralurban_cc,trump16_pct,clinton16_pct,otherpres16_pct,romney12_pct,obama12_pct,otherpres12_pct,cvap_pct,metro,rural,urban_metroadj,urban_not_metroadj
0,Alabama,Autauga,1001,75.683482,18.370906,2.572254,24.316518,1.838362,51.176225,40.037058,13.978456,53099.0,5.591657,12.417046,75.407229,10.002112,74.065601,42.002162,2.0,72.766588,23.769671,3.463741,72.618252,26.587832,0.793916,61.373802,1,0,0,0
1,Alabama,Baldwin,1003,83.178788,9.225603,4.366698,16.821212,3.269510,51.194928,35.474412,18.714851,51365.0,6.286843,9.972418,70.452889,7.842227,68.405607,42.279099,3.0,76.545712,19.385601,4.068687,77.358269,21.589444,1.052286,62.736377,1,0,0,0
2,Alabama,Barbour,1005,45.885624,47.888329,4.309762,54.114376,2.859397,46.498084,37.664387,16.528895,33956.0,12.824738,26.235928,87.132213,19.579752,81.364746,67.789635,6.0,52.096666,46.527844,1.375490,48.223130,51.368494,0.408376,51.381595,0,0,1,0
3,Alabama,Bibb,1007,74.765196,21.212121,2.223994,25.234804,1.351232,46.464646,37.329435,14.885699,39776.0,7.146827,19.301587,88.000000,15.020490,87.471774,68.352607,1.0,76.403220,21.249575,2.347205,72.826603,26.152019,1.021378,50.136441,1,0,0,0
4,Alabama,Blount,1009,87.657701,1.557951,8.727298,12.342299,4.271801,50.485235,37.240053,17.192916,46212.0,5.953833,19.968585,86.950243,16.643368,86.163610,89.951502,1.0,89.334844,8.425825,2.239331,86.465884,12.371907,1.162209,60.306387,1,0,0,0